### ISSUE TITLE
Data files and overlapping slices

### ISSUE THREAD

**Issue by emmanuelcharon** [sagishporer/hashcode-2018-practice-pizza#1]
Hi, 
it seems you beat my score (about 940K), so i'm curious about your solution. 

Can you provide the output files, so I can read them with my program and check they are correct? 

Are you allowing slices to overlap? It is forbidden in the problem statement.

**Comment by sagishporer** [comment]
No. Overlapping not allowed. The solution was checked with the online system while it was available.

I've added the output to the github repository.

**Comment by emmanuelcharon** [comment]
Thank you Sagi, I was able to download the files and confirm your solution is correct.
